version: "3.8"

services:
  app:
    image: "todo-dev-frontend-app"
    build:
      context: .
      dockerfile: dev.Dockerfile
    volumes:
      - ./:/usr/src/app
    ports:
      - 3080:3000
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:3100
    container_name: "todo-dev-frontend-app"
